#!/bin/sh

CDROM=$1

tmp=/tmp/fetch.$$

mkdir -p xc

echo "ls -R $CDROM/xc | sed -e '/^\$/d' | awk '"              >$tmp
echo "BEGIN {d=\"$CDROM/xc\"; dd=\"xc\"}"                     >>$tmp
echo '{if (/^\/.*:$/) {'                                      >>$tmp
echo '    d=substr($1,0,length($1)-1);'                       >>$tmp
echo "    dd=substr(d,length(\"$CDROM/x\"));"                 >>$tmp
echo '    print "mkdir -p " dd'                               >>$tmp
echo "  } else {"                                             >>$tmp
echo '    ln = d "/" $1;'                                     >>$tmp
echo '    print "if [ ! -d " ln " ]; then \
          (cd ./" dd "; ln -s " ln ") fi " '                  >>$tmp
echo "  }}'| sh"                                              >>$tmp

sh $tmp
rm -f $tmp
