# $FreeBSD: src/usr.sbin/lpr/Makefile,v 1.5.2.1 2000/12/26 17:50:37 gad Exp $

#SUBDIR=	common_source chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
#	filters filters.ru SMM.doc
SUBDIR= common_source lpc lpd lpq lpr lprm pac

MAINTAINER=	wollman@FreeBSD.org
MAINTAINER+=	gad@FreeBSD.org

.include <bsd.subdir.mk>

