# $FreeBSD: src/usr.sbin/lpr/Makefile,v 1.5 1999/08/28 01:16:45 peter Exp $

#SUBDIR=	common_source chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
#	filters filters.ru SMM.doc
SUBDIR= common_source lpc lpd lpq lpr lprm pac

.include <bsd.subdir.mk>


