# New ports collection makefile for:	v6tun
# Version required:	1.0
# Date created:		Tue Jun  9 13:38:11 JST 1998
# Whom:			Jun-ichiro itojun Itoh <itojun@itojun.org>
#
# $Id: Makefile,v 1.1.1.2 1999/08/10 09:14:46 itojun Exp $
#

DISTNAME=	v6tun-1.1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.kyoto.wide.ad.jp/IPv6/v6tun/

MAINTAINER=	itojun@itojun.org

.include "../../mk/bsd.pkg.mk"
