A
.Dd January 28, 2000
.Dt FREEVRRPD 8
.Os FreeBSD 4.3
.Sh NAME
.Nm freevrrpd
.Nd Virtual Redundancy Router Protocol Daemon for FreeBSD
.Sh SYNOPSIS
.Nm freevrrpd
.Sh DESCRIPTION
.Nm freevrrpd
is a RFC2338 compliant daemon, you can use VRRP protocol with multiple interfaces and multiple VRID. For each VRID defined in the configuration file,
.Nm freevrrpd
create a thread for managing a poll of one or multiple virtual IP addresses. Thios daemon work only in IPv4 environnement and not in IPv6 yet.
.Pp
you can eliminate all point of failures of your network with this utility. When 
.Nm freevrrpd 
is started, it reads /usr/local/etc/freevrrpd.conf file and go to background. All options are defined in this file. For more informations, you can read comments on this file.
.Pp
List of functionnalities :
.Bl -bullet -compact
.It
Support of multiples VRID
.It
Master announce state by sending multicast packets via BPF device
.It
Changing routes and IP in 3 seconds
.It
Doing gratuitous ARP requests to clean the ARP cache of all hosts
.It
Election between differents SLAVE servers with differents priorities
.It
Same host can be a SLAVE and MASTER at the same time for different VRID
.It
Autmatic downgrade to SLAVE state if a MASTER is up again
.It
Support of plain text authentication described in RFC2338
.It
Support netmask for virtual IP addresses
.Sh IMPLEMENTATION NOTES
This utility doesn't quit properly if you use the -KILL signal. If you want to stop freevrrpd, you can use kill [PID] and not kill -9 [PID], then it can delete virtual IP addresses and routes properly on shutdown.
.Sh BUGS
.Nm freevrrpd
is in active developpement, please send me bugs report and suggestions.
.Sh AUTHORS
.An Sebastien Petit Aq spe@bsdfr.org
.Sh HISTORY
first appeared in FreeBSD-4.3
