.include <bsd.own.mk>			# for EXPORTABLE_SYSTEM definition

SUBDIR+=rtsold ifmcstat ndp mping
SUBDIR+=traceroute6 rtadvd mld6query rrenumd icmp6dump
SUBDIR+=rip6query route6d faithd bgpd hroute6d pvcbridge pvcsif pvctxctl
SUBDIR+=ip6addrctl dhcp6

.include <bsd.subdir.mk>
