.include <bsd.own.mk>			# for EXPORTABLE_SYSTEM definition

SUBDIR+=rtsold ndp mping
#SUBDIR+=ifmcstat
SUBDIR+=traceroute6 rtadvd mld6query rrenumd icmp6dump
SUBDIR+=rip6query route6d faithd hroute6d pvcbridge pvcsif pvctxctl
SUBDIR+=ip6addrctl dhcp6
SUBDIR+=mip6control mip6stat

.include <bsd.subdir.mk>
