#	$NetBSD: Makefile,v 1.2 1999/03/23 18:10:59 drochner Exp $

TOP=		${.CURDIR}/..

.include "${TOP}/Makefile.inc"

#KERN?=	${.CURDIR}/../../../../sys/arch/i386/compile/INSTALL/netbsd
KERN?=	${.CURDIR}/../../../../sys/arch/i386/compile/INSTALL.v6/netbsd

.include "${TOP}/fdset-common/Makefile.inc"
