# $NetBSD$

DISTNAME=	echoping-2.2.0
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.internatif.org/pub/unix/echoping/

PATCHFILES=	echoping-2.2.0-v6-20000130.diff.gz
PATCH_SITES=	ftp://ftp.kame.net/pub/kame/misc/
PATCH_DIST_STRIP=	-p1

MAINTAINER=	itojun@kame.net

MAN1=		echoping.1

.include "../../mk/bsd.pkg.mk"
