# New ports collection makefile for:   ja-w3m-ssl
# Version required:            991028-2
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/japanese/w3m-ssl/Makefile,v 1.1.1.1 1999/11/21 20:57:35 sada Exp $
#

PKGNAME=       ja-w3m-ssl-${W3M_VER}
CATEGORIES=    japanese www

MASTERDIR=     ${.CURDIR}/../w3m
PKGDIR=        ${.CURDIR}/pkg
PLIST=         ${MASTERDIR}/pkg/PLIST.ja

JAPANESE=      Yes
USE_SSL=       Yes

.include "${MASTERDIR}/Makefile"
