# New ports collection makefile for:   ja-w3m-ssl
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/japanese/w3m-ssl/Makefile,v 1.5 2000/04/14 17:24:54 knu Exp $
#

PKGNAMEPREFIX=	ja-
PKGNAMESUFFIX=	-ssl
CATEGORIES=	japanese

MASTERDIR=	${.CURDIR}/../w3m
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST.ja

JAPANESE=	Yes
USE_OPENSSL=	RSA

.include "${MASTERDIR}/Makefile"
