# New ports collection makefile for:    geta
# Version required:     1.0
# Date created:         19 Apr 1999
# Whom:                 sumikawa
#
# $Id: Makefile,v 1.2 1999/08/24 17:34:12 sumikawa Exp $
#

DISTNAME=	pping-19990419
PKGNAME=	geta-19990419
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.kame.net/pub/kame/misc/

MAINTAINER=	sumikawa@kame.net

WRKSRC=		${WRKDIR}/pping
GNU_CONFIGURE=	yes

NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
