# New ports collection makefile for:	geta
# Date created:				19 Apr 1999
# Whom:					sumikawa
#
# $KAME: Makefile,v 1.3 2000/06/25 10:58:32 sumikawa Exp $
#

PORTNAME=	geta
PORTVERSION=	19990419
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.kame.net/pub/kame/misc/
DISTNAME=	pping-${PORTVERSION}

MAINTAINER=	sumikawa@kame.net

WRKSRC=		${WRKDIR}/pping
GNU_CONFIGURE=	yes

NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
