.include <bsd.own.mk>			# for EXPORTABLE_SYSTEM definition

SUBDIR+=ftp netstat rlogin rsh telnet vmstat finger tftp whois systat fstat

SUBDIR+=mcastread mcastsend mchat
SUBDIR+=altqstat

.include <bsd.subdir.mk>
