.include <bsd.own.mk>			# for EXPORTABLE_SYSTEM definition

#SUBDIR+=ftp rlogin rsh telnet finger tftp whois fstat
SUBDIR+=netstat vmstat

SUBDIR+=mcastread mcastsend mchat
SUBDIR+=altqstat

.include <bsd.subdir.mk>
