# New ports collection makefile for:	ja-w3m
# Version required:		991028-2
# Date Created:			8 Oct 1999
# Whom:				SADA Kenji <sada@FreeBSD.org>
#
# $FreeBSD: ports/japanese/w3m/Makefile,v 1.2 1999/11/14 02:08:31 steve Exp $
#

PKGNAME=	ja-w3m-${W3M_VER}
CATEGORIES=	japanese www

MASTERDIR=	${.CURDIR}/../w3m
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST.ja

JAPANESE=	Yes

.include "${MASTERDIR}/Makefile"
