APPENDDEF(`confLIBDIRS', `-L/usr/local/v6/lib')
APPENDDEF(`confLIBS', `-linet6')
APPENDDEF(`confENVDEF', `-DNETINET6')
dnl define(`confSTDIO_TYPE', `portable')
dnl APPENDDEF(`confENVDEF', `-DSFIO')
dnl APPENDDEF(`confLIBS', `-L/usr/pkg/lib -lsfio')
dnl APPENDDEF(`conf_sendmail_ENVDEF', `-DSTARTTLS')
dnl APPENDDEF(`conf_sendmail_LIBS', `-L/usr/pkg/lib -lssl -lcrypto')
