# $NetBSD$

DISTNAME=	mtr-0.41
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.bitwizard.nl/mtr/

PATCHFILES=	mtr-041-v6-19990903a.diff.gz
PATCH_SITES=	ftp://ftp.kame.net/pub/kame/misc/
PATCH_DIST_STRIP=	-p1

MAINTAINER=	itojun@itojun.org
HOMEPAGE=	http://www.BitWizard.nl/mtr/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--enable-ipv6

.include "../../mk/bsd.pkg.mk"
