# New ports collection makefile for:   w3m-ssl
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/www/w3m-ssl/Makefile,v 1.7 2000/04/14 17:24:56 knu Exp $
#

PKGNAMESUFFIX=	-ssl

MASTERDIR=	${.CURDIR}/../w3m
PKGDIR=		${.CURDIR}/pkg
PLIST=		${MASTERDIR}/pkg/PLIST

USE_SSL=	RSA

.include "${MASTERDIR}/Makefile"
