# New ports collection makefile for:   w3m-ssl
# Version required:            991028-2
# Date Created:                12 Oct 1999
# Whom:                        MANTANI Nobutaka <nobutaka@nobutaka.com>
#
# $FreeBSD: ports/www/w3m-ssl/Makefile,v 1.1.1.1 1999/11/21 20:54:44 sada Exp $
#

PKGNAME=       w3m-ssl-${W3M_VER}
CATEGORIES=    www

MASTERDIR=     ${.CURDIR}/../w3m
PKGDIR=        ${.CURDIR}/pkg
PLIST=         ${MASTERDIR}/pkg/PLIST

USE_SSL=       Yes

.include "${MASTERDIR}/Makefile"
