.Dd June 25, 1999
.Dt PVCBRIDGE 8
.Os BSD
.Sh NAME
.Nm pvcbridge
.Nd display or control ATM PVC bridging between two PVC sub interfaces
.Sh SYNOPSIS
.Nm pvcbridge
.Op get
.Ar interface
.Nm pvcbridge
.Li add
.Ar interface1
.Ar interface2
.Nm pvcbridge
.Li delete
.Ar interface1
.Ar interface2
.Sh DESCRIPTION
.Nm 
displays or controls bridging between two PVC sub interfaces.
ATM bridging allows to forward ATM frames at the driver level, 
neither IP address nor IP routing is required for the PVC sub
interfaces.
An ATM VC should be assgined to each PVC sub interface by 
.Xr pvctxctl 8 .
.Pp
With keyword
.Dq Li get ,
.Nm 
displays the current bridge setting of the given PVC sub interface.
The
.Ar inerface
parameter must be an ATM PVC sub interface created by
.Xr pvcsif 8 .
With keyword
.Dq Li add
or
.Dq Li delete ,
.Nm
sets or deletes bridging between the given two ATM PVC sub interfaces.
With no keyword,
.Dq Li get
is assumed.
.\"
.Sh EXAMPLE
For example, to set up bridging between VC:201 on en0 and VC:202 on en1:
.Pp
.Bd -literal
# pvcsif en0      		# creates pvc0
# ifconfig pvc0 up		# up pvc0
# pvctxctl pvc0 201 -b 45M	# assign vc
# pvcsif en1      		# creates pvc1
# ifconfig pvc1 up		# up pvc1
# pvctxctl pvc1 202 -b 45M	# assign vc
# pvcbridge pvc0 pvc1		# set bridging
.Ed
.\"
.Sh SEE ALSO
.Xr ifconfig 8 , 
.Xr pvcsif 8 ,
.Xr pvctxctl 8
