# $NetBSD$
#

DISTNAME=	pchar-1.2
CATEGORIES=	net
MASTER_SITES=	http://www.employees.org/~bmah/Software/pchar/

MAINTAINER=	itojun@itojun.org
HOMEPAGE=	http://www.employees.org/~bmah/Software/pchar/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=--with-ipv6=/usr/local/v6

.include "../../mk/bsd.pkg.mk"
