#	from: @(#)Makefile	8.1 (Berkeley) 6/6/93
#	$NetBSD: Makefile,v 1.14 1997/10/25 06:58:06 lukem Exp $

PROG=	dhcp6relay
SRCS=	dhcp6relay.c common.c
MAN8=	dhcp6relay.8

.include <bsd.prog.mk>

.PATH:	${SRCDIR}
