# New ports collection makefile for:    root
# Version required:     1.0
# Date created:         26 Nov 1998
# Whom:                 sumikawa
#
# $Id: Makefile,v 1.1 1999/08/09 01:37:01 itojun Exp $
#

DISTNAME=	pping-19990419
PKGNAME=	geta-19990419
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.kame.net/pub/kame/misc/

MAINTAINER=	sumikawa@kame.net

WRKSRC=		${WRKDIR}/pping
GNU_CONFIGURE=	yes

NO_INSTALL_MANPAGES=	yes

.include <bsd.port.mk>
