.\"	$KAME: shisa.8,v 1.2 2007/02/06 05:58:52 t-momose Exp $
.\"
.\" Copyright (C) 2004-2007 WIDE Project.
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd Feb 2, 2007
.Dt SHISA 8
.Os KAME
.Sh NAME
.Nm shisa
.Nd Mobile IPv6/NEMO implementation
.\"
.Sh DESCRIPTION
.Nm
is an implemenation of Mobile IPv6(MIPv6) based on RFC3775, and NEMO based on RFC3963 for BSD operating systems.
.Nm
supports most of features specified RFC3775, RFC3776 and RFC3963 to be a mobile node, a correspondent node, a home agent and a mobile router.
And also some other specifications partially.
.Pp
.Nm
consists of kernel parts and several userland daemons.
Operating packets such as inserting or extracting extention headers specialized for MIPv6, and handling tunnelled packets are done in the kernel side.
Meanwhile, signaling packets such as binding update, binding acknowledgement are handled in userland daemons.
.Pp
And
.Nm
intorduces a new interface between kernel and userland, which is called 'mobility socket'.
.\"
.Sh SEE ALSO
.Xr mnd 8
.\".Xr mrd 8
.Xr cnd 8
.Xr had 8
.Xr babymdd 8
.Xr nemonetd 8
.Pp
.Xr http://www.mobileip.jp/
.\"
.Sh HISTORY
The name of
.Nm
is derived from a name of a lion-shaped roof ornament of Okinawa, the south island in Japan.
The shisa implemenation team had the 1st camp in Okinawa in 2004 spring and 
.Nm
was born there.
The team named the MIP6/NEMO code
.Nm
after the famous ornament in the birthplace.
.Pp
And The
.Nm
was merged into the kame source tree in December 2004.
.Sh BUGS
Nothing.
