.\"	$KAME: natpt.conf.5,v 1.22 2004/04/16 04:47:23 fujisawa Exp $
.\"
.\" Copyright (C) 1995, 1996, 1997, 1998, 1999, 2000 and 2001 WIDE Project.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\" Note: The date here should be updated whenever a non-trivial
.\" change is made to the manual page.
.Dd December 25, 1999
.Dt NATPT.CONF 5
.\" Note: Only specify the operating system when the command
.\" is FreeBSD specific, otherwise use the .Os macro with no
.\" arguments.
.Os KAME
.\"
.Sh NAME
.Nm natpt.conf
.Nd configuration file for KAME NAT-PT
.\"
.Sh DESCRIPTION
.Nm
describes the configuration file format for
.Xr natptconfig 8 .
However
.Xr natptconfig 8
does not have default configuration file, this filename
.Pq Nm
is as an example.
.Pp
This file consists of a sequence of statements.  Each statement is
beginning with directive.  Lines beginning with
.Ql #
are comments.  Blank line is ignored.
.Pp
Each rule processed by this translater is added in the kernel internal
list if there is no parsing problems.  When more than one rule is
described, rule that has an error is not added, but the rule that has
no error is added to this list.
.Pp
.\"
.Sh DIRECTIVES
Keywords and special characters that the parser expects exactly are
displayed using
.Sy this
font.  Parameters are specified with
.Em this
font.  Square brackets
.Pq So \&[ Sc and So \&] Sc
are used to show optional keywords and parameters.  Parentheses
.Pq So \&( Sc and So \&) Sc
are used to group keywords and parameters when necessary.  The
vertical bar
.Pq Ql \&|
is used to indicate a choice between optional
parameters.
.Pp
You can put all directives into file and process using
.Fl f
option
.Po see
.Xr natptconfig 8
.Pc ,
here we describe directives mainly executed from command line.
The following directives are available in the configuration file.
.Bl -tag -width Ds
.\"
.It Xo Sy prefix Ar prefix
.Xc
Set NAT-PT prefix.  Packet addressed to this prefix is subject to
translate.  Prefix length is always assumed as 96 bits.
.Pp
This prefix should be a Global Unicast Addresses.  When you specify a
link-local or multicast address as a NAT-PT prefix, translator cannot
send a translated packet to the network.
.\"
.It Xo Sy map Op Ar number
.Sy from ...
.Xc
Add translation rule into the kernel internal list.  The rules for
returning packet is not appear in this map list. Rule is arranged with
ascending order according to this number.
.Ar number
is number of translation rule.  This is a non negative integer and it
is supposed to be 65535 when omitted.  See the
.Em RULE NUMBER
section below for more information.
.Pp
The following formats are available.  With this following examples,
all the rule number is omitted.
.Bl -tag -compact -width XXX
.Pp
.\"	map from any6               to 202.249.11.250 port 28672 - 32767
.\"	map from 3ffe:501:4819::/48 to 202.249.11.250 port 28672 - 32767
.It Xo Sy map from any6 to Ar v4addr
.Op Sy port Ar num Sy - Ar mum
.Xc
.It Xo Sy map from Ar v6addr
.Op Sy \&/ Ar num
.Sy to Ar v4addr
.Op Sy port Ar num Sy - Ar mum
.Xc
Translate IPv6 packet to IPv4 packet.
.Pp
The former is translate IPv6 packet coming from arbitrary host.  The
latter is translate IPv4 packet coming from specified host or address
range.  Both rules translate incoming IPv6 packet to packet coming out
of specified IPv4 address.  The number after
.Sy \&/
specifies address mask.  When address mask is not specified, it is
treated as if
.Sy \&/
128 is specified.  If
.Sy port
is specified, convert source port number into the number that is not
used with specified range.  If not, source port number is not
converted.
.Pp
.\"	map from 202.249.11.251 dport 65305 to 3ffe:0501:041c::1 dport 23
.It Xo Sy map from
.Ar v4addr Op Sy dport Ar num
.Sy to
.Ar v6addr
.Op Sy dport Ar num
.Xc
Translate IPv4 packet to IPv6 packet.
.Pp
This format was changed to the format using
.Sy daddr/dport .
It is recommended not to use this format because this format may be
abolished in the future.  Use the following rule instead.
.Pp
.\"	map from daddr 10.21.32.252 to daddr 2001:0240:010a:5555:0260:08ff:feb0:96f4
.It Xo Sy map from daddr Ar v4addr
.Sy to daddr Ar v6addr
.Xc
.It Xo Sy map from daddr Ar v4addr Sy dport Ar v4port
.Sy to daddr Ar v6addr Sy dport Ar v6port
.Xc
Translate IPv4 packet to IPv6 packet.
.Pp
The former is translate IPv4 packet destined to specified IPv4 address
to IPv6 packet going to specified address.  Port number is not
changed.
.Pp
The latter is translate IPv4 packet destined to
.Em v4addr
and
.Em v4port
to IPv6 packet destined to
.Em v6addr
and
.Em v6port .
Both rules translate both source and destination address.
.Pp
.\"	map from 10.0.0.3/8 to 202.249.11.252 port 28672 - 32767
.It Xo Sy map from Ar v4addr
.Op Sy \&/ Ar num
.Sy to Ar v4addr
.Op Sy port Ar num Sy - Ar mum
.Xc
Translate IPv4 packet to IPv4 packet.
.Pp
IPv4 packet coming from specified host or address range is translated
to packet coming out of specified IPv4 address.  The number after
.Sy \&/
specifies address mask.  When address mask is not specified, it is
treated as if
.Sy \&/
32 is specified.  If
.Sy port
is specified, convert source port number into the number that is not
used with specified range.  If not, source port number is not
converted.  This facility
.Pq IPv4-IPv4 translation
is same as a lot of NAT used in the world.
.El
.Pp
All the rules mentioned above
.Pq Sy map from ...
can have
.Op Sy proto Ar protcol
option.  This option specifies the protocol, specify
.Sy icmp tcp
and
.Sy udp
separated by
.Ql Sy \&/ .
For example,
.Sy proto tcp/udp .
There is no meaning in order of protocol to specify, and there is no
syntax error when you specify more then one same protocol.  This
.Sy proto
option must be specified at the last of syntax except a case of using
.Sy bidir
option.
.Pp
Option
.Sy bidir
is used when specified bi-directional NAT.  This NAT binds global
address to private address one-on-one statically.  Sessions can be
initiated from hosts in the public network as well as the private
network.  So, if you can set nat session as bidirectional, you can
connect to the host located behind this NAT from public IPv4 network.
.Pp
Here are some important points to consider when using
.Sy bidir
option:
.Bl -bullet
.It
This
.Sy bidir
option must be specified at the last of syntax.
.It
Number of address that specify by
.Sy from
and
.Sy to
is 1.  You can not specify more than one address here because
translation is ono-on-one.
.It
Does not translate port number.  So You need several IPv4 address, an
equal number of host to be connected to.
.It
It is recommended that the IP address which described after
.Sy to
is set different from IP address assigned to interface of this NAT
box.  Or NAT can not receive a packet destined to NAT itself because
this NAT translate the packet which come to this IP address
unconditionally.
.Pp
.Fl alias
option of ifconfig command is usable to do this purpose.  See
.Xr ifconfig 8
for more detail.
.El
.\"
.It Xo Sy map flush
.Xc
Remove all translation rules from the kernel.  There is no way to
remove only one rule.
.\"
.It Xo Sy map
.Pq Sy enable|disable
.Xc
Enable or disable translation.  Initial status is disabled.
.\"
.It Xo Sy set Ar var Ar = Ar value
.Xc
Set the value to the variable.  Value can use decimal or hexadecimal
(begin with 0x) notation.  Variables are divided into three
categories,
.Sq tslot ,
.Sq caddr
and
.Sq others .
Description of each category and of variables belonging to it is as
follows.
.Pp
The following variables are belonging to
.Sq others
and are displayed with
.Sq show variables
subcommand.
.Pp
.Bl -tag -width XXX -offset XXX -compact
.It translation
The flag which does Protocol translation.  If this value is not zero,
protocol translation is done.  Otherwise, protocol translation is not
done.  This value is also set by
.Sq map
subcommand.
.It debug
This is for debug.
.It dump
When set, dump mbuf or ip packet.  You must run natptlog command to
show its dump.
.It prefix
NAT-PT prefix. This value is set by
.Sq prefix
subcommand.
.It forcefragment4
If set to non-zero value, translator translates ipv4 packet into ipv6
packet even if its DF bit is set and its size exceeds 1260 octets.  if
ipv4 packet size exceeds 1260 octets, packet is divided into two ipv6
packet with fragment header.
.Pp
Because this behavior ignores meaning of DF bit, you had better not
use it if possible.
.It uselog
If set to non-zero value, log output goes to natptlog system.  You
need to invoke natptlog to read this log message
.It usesyslog
If set to non-zero value, log output goes to syslog system.  Log
facility of this time is LOG_KERNEL.  See
.Xr syslog.conf 5
for more detail.  There is no way to distinguish between this message
and other message from kernel now.
.El
.Pp
The following variables are belonging to
.Sq caddr
and are displayed with
.Sq show variables caddr
subcommand.  You can not set these variables.  These are read only and
are for debug.
.Pp
.Bl -tag -width XXX -offset XXX -compact
.It cSlotHead
Start address of the configuration table.
.It tSlotHead
Start address of the current translation table.
.El
.Pp
The following variables are belonging to
.Sq tslot
and are displayed with
.Sq show variables tslot
subcommand.  These variables are all related with timer, and unit of
time is a second.
.Pp
.Dq tSlot
is a current translation table and holds an translation information.
If translation is disabled or there is no translation, this table size
is zero, and this size increases or decreases according to translation
process.  This table has a time watching process and several valid
lifetimes.  Time watching process watches every entry of this table
and eliminates an entry which exceed its lifetime.  Lifetime varies by
what kind of protocol this slot translates into.  Detail of each
lifetime is described below.
.Pp
.Bl -tag -width XXX -offset XXX -compact
.It tSlotTimer
This is a time interval to invoke the time watching process.  If set
to zero value time-watching-process invokes continuously, it may bear
an unexpected result; e.g. translation slot is not registered, and
translation never occurs.
.Pp
If set to 10 seconds, and lifetime described below is set to 20
seconds, slot entry exists for maximum 30 seconds for minimum 20
seconds.
.It maxTTLany
This is one of lifetime and this is valid when protocol is not a TCP,
UDP nor ICMP.
.It maxTTLicmp
This is one of lifetime and is related to ICMP/ICMPv6.
.It maxTTLudp
This is one of lifetime and is related to UDP.
.It maxTTLtcp
This is one of lifetime and is related to TCP and this is valid when
status of TCP session is as follows.
.Bl -inset -compact
.It -
TCPS_ESTABLISHED
.El
.It tcpt_2msl
This is one of lifetime and is related to TCP and this is valid when
status of TCP session is as follows.
.Bl -inset -compact
.It -
TCPS_CLOSED
.It -
TCPS_TIME_WAIT
.El
.It tcp_maxidle
This is one of lifetime and is related to TCP and this is valid when
status of TCP session is as follows.
.Bl -inset -compact
.It -
TCPS_SYN_SENT
.It -
TCPS_SYN_RECEIVED
.It -
TCPS_FIN_WAIT_1
.It -
TCPS_FIN_WAIT_2
.El
.It maxFragment
This is one of lifetime and is related to fragmented packet.  You do
not need to change this usually.
.El
.Pp
See
.Xr natptconfig 8
for more detail of the
.Sq natptconfig show
subcommand.
.El
.\"
.Sh RULE NUMBER
Here are some important points to consider when attatching rule
number:
.Bl -bullet
.It
Rule is arranged with ascending order according to this number.  This
rule number is a non negative integer and it is supposed to be 65535
when omitted.  You can use an integer greater than 65535 as a rule
number.
.It
If rule having the same number exists in the kernel, new rule is
appended to the last of rule having the same number.
.It
Number 0 is an exception of above.  The rule having this number is
always added at the beginning of rule list.
.El
.\"
.Sh EXAMPLES
The following example is typical NAT-PT configuration.  IPv6 packets
which has the prefix
.Em 3ffe:ffff:ffff:ffff::/96
are translated into IPv4 packet.
Source address of the translated IPv4 packets are set to
.Em 172.16.11.22 .
.Pp
.Bd -literal -offset indent
prefix 3ffe:ffff:ffff:ffff::
map from any6 to 172.16.11.22
map enable
.Ed
.\"
.Sh COMPATIBILITY
Caution is needed because some syntax was changed.  This change was
done at end of September, 2001.  The following is changed point of
syntax.
.Bl -bullet
.It
.Ql interface
directive was removed.
.It
about
.Ql prefix
directive, word
.Ql natpt
became needless.
.It
about
.Ql map
directive, word
.Ql inbound
and
.Ql outbound
became needless.  Use
.Ql dport
when you want to change destination port number.  i.e.,
.Bd -literal -offset XXXX
map from 202.249.11.251 dport 65305 to 3ffe:0501:041c::1 dport 23
.Ed
.El
.\"
.Sh SEE ALSO
.Xr natptconfig 8 ,
.Xr ifconfig 8
.\"
.Sh HISTORY
The
.Xr natptconfig
command first appeared in WIDE/KAME IPv6 protocol stack kit.
.\"
.Sh BUGS
