# ex:ts=8
# New ports collection makefile for:    pchar
# Version required:     1.0
# Date created:         Thu Nov  4 14:11:56 JST 1999
# Whom:                 sumikawa@kame.net
#
# $Id: Makefile,v 1.1.1.1 1999/11/04 05:50:18 sumikawa Exp $
#

DISTNAME=       pchar-1.0
CATEGORIES=	net
MASTER_SITES=	http://www.ca.sandia.gov/~bmah/Software/pchar/

MAINTAINER=	sumikawa@kame.net

GNU_CONFIGURE=	yes
CONFIGURE_ARGS=	--with-ipv6=/usr/local/v6

MAN1=		pchar.1

.include <bsd.port.mk>
