.\"
.\"	$KAME: mip6stat.8,v 1.5 2001/03/29 05:34:29 itojun Exp $
.\"
.Dd Mar 15, 2001
.Dt MIP6STAT 8
.Os KAME
.\"
.Sh NAME
.Nm mip6stat
.Nd Show Mobile IPv6 configuration
.\"
.Sh SYNOPSIS
.Nm mip6stat
.Fl a
.Op Fl ln
.Nm mip6stat
.Fl A
.Nm mip6stat
.Fl c
.Op Fl ln
.Nm mip6stat
.Fl C
.Nm mip6stat
.Fl f
.Op Fl ln
.Nm mip6stat
.Fl F
.Nm mip6stat
.Fl m
.Op Fl ln
.Nm mip6stat
.Fl M
.Nm mip6stat
.Fl p
.Op Fl l
.Nm mip6stat
.Fl P
.Nm mip6stat
.Fl u
.Op Fl ln
.Nm mip6stat
.Fl U
.Nm mip6stat
.Fl h
.Sh DESCRIPTION
The
.Nm
command displays or clears the contents of various Mobile
IPv6-related data structures. Some commands may require
superuser privileges.
.\"
.Ss OPTIONS
.Bl -tag -width Ds
.It Fl h
Show a simple usage information.
.It Fl a
Print home agent list.
.It Fl A
Clear home agent list.
.It Fl c
Print binding cache.
.It Fl C
Clear binding cache.
.It Fl f
Print static address list.
.It Fl F
Clear static address list.
.It Fl m
Print home address.
See below for state descriptions.
.It Fl M
Clear home address.
.It Fl p
Print configuration.
.It Fl P
Restore default configuration.
.It Fl u
Print binding update list.
.It Fl U
Clear binding update list.
.It Fl n
Show network addresses as numbers.
This option
may be used with any of the display formats.
.It Fl l
Show more infomation.
This option
may be used with any of the display formats.
.El
.Sh MOBILE NODE STATES
The Mobile Node can be in the following states (returned by
.Nm
.Fl m
)
.Bl -column XXXXX de-registering:
Undef	Undefined:	No routers in sight
Home	Home:		Home, and successfully de-registered
Dereg	De-registering:	At home and waiting for Binding Ack
Notrg	Not registed:	At foreign and waiting for Binding Ack
Reg'd	Registered:	At foreign and registered
Rereg	Re-registering:	At same foreign and waiting for Binding Ack
NewCO	New C/O Addr:	At new foreign and waiting for Binding Ack
.El
.Sh AUTHORS
Magnus Braathen, Mattias Pettersson <mattias.pettersson@era.ericsson.se>
