SUBDIR+=lpr inetd

SUBDIR+=bgpd dtcp faithd gifconfig hroute6d icmp6dump ifmcstat mld6query mping \
	ndp pim6dd pim6sd prefix route6d rrenumd setkey tcpdump traceroute \
	traceroute6 rtsold rtadvd rip6query racoon
#SUBDIR+=inet6d

.include <bsd.subdir.mk>
