.\"	$KAME: rip6query.8,v 1.8 2006/10/25 05:45:59 jinmei Exp $
.\"
.\" Copyright (C) 1998 and 1999 WIDE Project.
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd October 7, 1999
.Dt RIP6QUERY 8
.Os KAME
.Sh NAME
.Nm rip6query
.Nd RIPng debugging tool
.\"
.Sh SYNOPSIS
.Nm
.Op Fl I Ar interface
.Op Fl P Ar source port
.Op Fl h Ar hop limit
.Op Fl p Ar prefix
.Op Fl s Ar source address
.Op Fl w Ar time
.Ar destination
.\"
.Sh DESCRIPTION
.Nm
requests remote RIPng daemon on
.Ar destination
to dump RIPng routing information.
It can also send a RIPng response message when
.Fl r
option is specified.
.Fl I
lets you specify outgoing
.Ar interface
for the query packet.
This was useful for a link-local address specified as
.Ar destination
to disambiguate the outgoing link, but now it is mostly obsoleted
because the link can be specified using the textual representation
for scoped addresses as defined in RFC4007.
When the
.Fl P
or
.fl s
option is specified, the source port or the source address for the
outgoing message packet is set to the specified value, respectively.
Similarly, the
.Fl h
option specifies the hop limit value of the IPv6 header for the
outgoing packet.
The
.Fl p
option specified a particular prefix for the request or response
message.  For a request message, it means a request for the route to
the destination specified by the prefix;
by default,
.Nm
requests the entire routing table of the remote router.
For a response message, this option must be given and specifies the
destination of the RTE.
.Fl w
specifies the time in seconds to wait for the initial
response from a gateway.
The default value is 5 seconds.
When the response message is generated,
this option is ignored and
.Nm
does not wait at all and 
.\"
.Sh SEE ALSO
.Xr route6d 8
.\"
.Sh HISTORY
The
.Nm
command first appeared in WIDE Hydrangea IPv6 protocol stack kit.
