SUBDIR+=bgpd dtcp faithd gifconfig hroute6d icmp6dump \
	mping mld6query ndp pim6dd pim6sd prefix rip6query route6d \
	rrenumd rtadvd rtsold setkey traceroute traceroute6 scope6config
SUBDIR+=altqd natptconfig natptd natptlog pvcbridge pvcsif pvctxctl
#SUBDIR+=ifmcstat
#SUBDIR+=pma
#SUBDIR+=racoon
SUBDIR+=mip6config mip6stat

.include <bsd.subdir.mk>
