SUBDIR+=bgpd dtcp faithd gifconfig hroute6d icmp6dump \
	mping mld6query ndp pim6dd pim6sd prefix rip6query route6d \
	rrenumd rtadvd rtsold setkey traceroute traceroute6
SUBDIR+=altqd natptconfig natptd natptlog pvcbridge pvcsif pvctxctl tbrconfig
#SUBDIR+=ifmcstat
SUBDIR+=racoon
SUBDIR+=mip6config mip6stat

.include <bsd.subdir.mk>
