SUBDIR+=bgpd dtcp faithd gifconfig hroute6d icmp6dump \
	mping mld6query ndp pim6dd pim6sd prefix rip6query route6d \
	rrenumd rtadvd rtsold setkey traceroute traceroute6
SUBDIR+=altqd natptconfig natptlog pvcbridge pvcsif pvctxctl tbrconfig
#SUBDIR+=ifmcstat
SUBDIR+=racoon

.include <bsd.subdir.mk>
