#	$NetBSD: Makefile,v 1.1 1998/06/12 23:23:07 cgd Exp $

KDIR=	/sys/altq
INCSDIR= /usr/include/altq

INCS+=	altq.h altq_afmap.h altq_blue.h altq_cbq.h altq_cdnr.h altq_classq.h \
	altq_conf.h altq_fifoq.h altq_flowvalve.h altq_hfsc.h altq_red.h \
	altq_rio.h altq_rmclass.h altq_rmclass_debug.h altq_var.h altq_wfq.h \
	if_altq.h

.include <bsd.kinc.mk>
