SUBDIR+=faithd hroute6d icmp6dump \
	mping mld6query ndp rip6query route6d \
	rrenumd rtadvd rtsold setkey traceroute traceroute6
#SUBDIR+=altqd pvcbridge pvcsif pvctxctl tbrconfig
SUBDIR+=ifmcstat
#SUBDIR+=racoon
#SUBDIR+=pim6dd pim6sd 
SUBDIR+=ip6addrctl
SUBDIR+=dhcp6
SUBDIR+=shisad

.include <bsd.subdir.mk>
