SUBDIR+=faithd gifconfig hroute6d icmp6dump \
	mping mld6query ndp pim6dd pim6sd rip6query route6d \
	rrenumd rtadvd rtsold setkey traceroute traceroute6
SUBDIR+=altqd pvcbridge pvcsif pvctxctl tbrconfig
SUBDIR+=ifmcstat
SUBDIR+=racoon
SUBDIR+=mip6control had mip6stat
SUBDIR+=ip6addrctl
#SUBDIR+=natptconfig natptlog

.include <bsd.subdir.mk>
