.\"	$KAME: dsadd.8,v 1.3 2003/01/10 09:10:13 sakane Exp $
.\"
.\" Copyright (C) 2002 WIDE Project.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd December 27, 2002
.Dt DSADD 8
.Os KAME
.\"
.Sh NAME
.Nm dsadd
.Nd Dead Security Association Detection Daemon
.\"
.Sh SYNOPSIS
.Nm dsadd
.Op Fl c Ar number
.Op Fl i Ar time
.Op Fl P Ar priorify
.Op Fl LESd
.\"
.Sh DESCRIPTION
.Nm
detects and deletes the dead security association.
.Nm
searches the security association database in the kernel periodically,
then sends ICMP echo requests to the peer of each SA.
if any ICMP echo reply won't be back,
.Nm
will delete the SA immediately.
.Bl -tag -width Ds
.It Fl c
specify the number of icmp echo packet to be sent.
default is 2 times.
.It Fl i
(a) if the current round takes more than the specified
time in seconds the next round will start immediately
after the current will finish.  (b) otherwise the next
will start after the specified time from the current
first check.
default is 300 seconds.
.Bd -unfilled -literal -offset indent
(a)
+----- first round -----+---- second round --...
+-- specified time --+

(b)
+----- first round -----+      +---- second round --...
+------- specified time -------+
.Ed
.It Fl P
specify the priority used by logger(1).
default is
.Qo
user.notice
.Qc .
.It Fl L
force to check only once.
.It Fl E
don't delete the SA even if the SA looks dead.
.It Fl S
don't tell syslog(8) what the SA has been deleted.
.It Fl d
debug mode.
.\"
.\".Sh RETURN VALUES
.\"
.\".Sh FILES
.\"
.Sh SEE ALSO
.Xr logger 1 ,
.Xr setkey 8 ,
.Xr syslogd 8
.\"
.\".Sh HISTORY
.\"
.Sh BUGS
.Nm
can only detect the dead SAs which based an IP address.
For example, when the SA is only for a TCP session,
.Nm
cannot detect if the SA is dead or alive because
.Nm
uses ICMP packets.
the peer sends back a response even if the SA is dead.
