SUBDIR+=trpt

SUBDIR+=bgpd dtcp faithd hroute6d icmp6dump ifmcstat mld6query mping \
	ndp pim6dd pim6sd prefix route6d rrenumd traceroute \
	traceroute6 rtsold rtadvd rip6query lpr dhcp6 pppd
SUBDIR+=natptconfig natptd natptlog
SUBDIR+=racoon
SUBDIR+=pvcbridge pvcsif pvctxctl
SUBDIR+=altqd tbrconfig
#SUBDIR+=inet6d

SUBDIR+=mip6config mip6stat

.include <bsd.subdir.mk>
