SUBDIR+=trpt traceroute

SUBDIR+=faithd icmp6dump ifmcstat mld6query mping \
	ndp pim6dd pim6sd route6d \
	traceroute6 rtsold rtadvd rip6query hroute6d ip6addrctl
#SUBDIR+=pvcbridge
SUBDIR+=pvcsif pvctxctl
SUBDIR+=altqd tbrconfig
#SUBDIR+=inet6d
SUBDIR+=racoon
SUBDIR+=dhcp6
SUBDIR+=shisad

.include <bsd.subdir.mk>
