# $NetBSD: Makefile,v 1.36 1998/09/05 20:20:03 frueauf Exp $
# FreeBSD Id: Makefile,v 1.117 1997/08/16 03:11:52 gpalmer Exp 
#

.include "../mk/bsd.prefs.mk"

    SUBDIR += apache13
    SUBDIR += lynx
    SUBDIR += squid11
    SUBDIR += w3m
    SUBDIR += wwwoffle

.include "../mk/bsd.pkg.subdir.mk"
