.\"	$KAME: mip6control.8,v 1.14 2004/01/28 04:57:01 t-momose Exp $
.\"
.\" Copyright (C) 1995, 1996, 1997, 1998, 1999, 2000, 2001 WIDE Project.
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd Aug 27, 2001
.Dt MIP6CONTROL 8
.Os KAME
.\"
.Sh NAME
.Nm mip6control
.Nd control KAME/MIP6 features
.\"
.Sh SYNOPSIS
.Nm
.Op Fl i Ar ifname
.Op Fl abcghlmMnNw
.Op Fl H Ar home_prefix
.Op Fl P Ar prefixlen
.Op Fl A Ar home_agent_global_addr
.Op Fl L Ar home_agent_linklocal_addr
.Op Fl C Ar addr
.Op Fl u Ar address#port
.Op Fl v Ar address#port
.Op Fl F Ar ifp1[:ifp2[:ifp3]]
.Op Fl S Ar 0|1
.Op Fl D Ar 0|1
.Sh DESCRIPTION
.Nm
sets/gets KAME/MIP6 related information.
If no argument is specified,
.Nm
shows the current status of the node.
.Bl -tag -width Ds
.It Fl i Ar ifname
Speify home interface of the mobile node.
The default value is hif0.
.It Fl H Ar home_prefix
Set
.Ar home_prefix
as a home prefix of the mobile node.
You must specify the prefix length of
.Ar home_prefix
with
.Fl P
option.
.It Fl P Ar prefixlen
Specify the length of the prefix to be assinged to the mobile node.
Use with
.Fl H
option.
.It Fl A Ar home_agent_global_address
Specify the global address of the home agent of this mobile node.
If your home agent supports DHAAD (Dynamic Home Agent Address Discovery),
you need not use this switch.
Use with
.Fl L
option.
.It Fl L Ar home_agent_linklocal_address
Specify the linklocal address of the home agent of this mobile node.
If your home agent supports DHAAD (Dynamic Home Agent Address Discovery),
you need not use this switch.
Use with
.Fl A
option.
.It Fl m
Start acting as a mobile node.
.It Fl M
Stop acting as a mobile node.
.It Fl n
Show network addresses as numbers.
.It Fl h
Show the home prefixes currently set to this mobile node.
.It Fl a
Show the home agents list.
.It Fl b
Show the binding update list.
.It Fl g
Start acting as a home agent.
.It Fl c
Show the binding cache entries.
.It Fl C Ar addr
Remove the binding cache entry specified by
.Ar addr .
.Ar addr
is a home address of the binding cache entry.
If :: is specified,
.Nm
removes all binding cache entries.
.It Fl l
Show information in a long format.
.It Fl u Ar Address#Port
Add a rule that MN doesn't add a Home Address option to the outgoing packet.
.It Fl v Ar Address#Port
Delete the rule which specified one.
.It Fl w
Show the rule.
.It Fl F Ar ifp1[:ifp2[:ifp3]]
Set preferrable network interfaces for CoA selection.
Specify nothing to remove the preferences.
.It Fl S Ar 0|1
When set to 0, the IPsec protection check of the incoming binding updates
and binding acks will not be performed (always pass the check).
.It Fl D Ar 0|1
When set to 0, no debug messages are printed.
.It Fl N
Show the list of nonces that this host maintains as a correspondent node.
The first column is the number of nonce index and the second is a nonce value.
.El
.\"
.Sh EXAMPLES
To make a node act as a mobile node, issue the following commands as a root.
.Bd -literal
root# mip6control -i hif0 -H 2001:200:1:1:: -P 64
root# mip6control -m
.Ed
.Pp
Replace 2001:200:1:1:: with your home network prefix.
.Pp
To make a node act as a home agent, issue the following commands as a root.
.Bd -literal
root# mip6control -g
.Ed
.Pp
To set a rule to avoid adding home address option when quering DNS, issue the following commands as a root.
.Bd -literal
root# mip6control -u ::#53
.Ed
.\"
.Sh HISTORY
The
.Nm
command first appeared in WIDE/KAME IPv6 protocol stack kit.
.\"
.Sh BUGS
Many :).
