.\"
.\" Copyright (C) 1998 and 1999 WIDE Project.
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"     $Id: dhcp6s.8,v 1.1 1999/09/12 11:45:14 itojun Exp $
.\"
.Dd Sep 12, 1999
.Dt DHCP6S 8
.Os KAME
.Sh NAME
.Nm dhcp6s
.Nd tiny DHCPv6 server
.\"
.Sh SYNOPSIS
.Nm
.Op Fl d
.Op Fl n Ar dnsserv
.Ar interface
.\"
.Sh DESCRIPTION
.Nm
replies to DHCPv6 client and replies as DHCPv6 server.
.\"
.Sh SEE ALSO
.Xr dhcp6c 8
.\"
.Sh HISTORY
The
.Nm
command first appeared in WIDE/KAME IPv6 protocol stack kit.
.\"
.Sh BUGS
.Nm
is incomplete and violates DHCPv6 protocol spec, in several aspects.
To name a few:
.Bl -enum
.It
it does not handle cases when client contacts server via relay agent,
.It
it does not manage client-agent mapping table nor client XID,
.It
it does not handle resource allocations
.Pq such as IPv6 address ,
.It
it does not implement DHCPv6 release nor reconfigure message handling.
.El
