.\"     $KAME: mdnsd.8,v 1.6 2000/05/31 04:02:42 itojun Exp $
.\"
.\" Copyright (C) 2000 WIDE Project.
.\" All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd May 21, 1999
.Dt MDNSD 8
.Os KAME
.Sh NAME
.Nm mdnsd
.Nd multicast DNS resolver
.\"
.Sh SYNOPSIS
.Nm
.Op Fl 46D
.Op Fl d Ar dnsserv
.Op Fl h Ar hostname
.Op Fl p Ar inport
.Op Fl P Ar outport
.Fl i Ar intface
.\"
.Sh DESCRIPTION
.Nm
serves as multicast DNS resolver.
.Nm
will get unicast DNS queries from local node,
and forward the queries toward multicast DNS address on interface specified by
.Ar intface .
Whenever a reply comes back against the multicast queries,
.Nm
will forward the reply to the original querier.
.Pp
.Nm
will also reply to multicast DNS queries from other nodes.
.Pp
.Bl -tag -width Ds
.It Fl 4
.It Fl 6
Controls the address family to use for DNS transport.
.It Fl D
Enable trace messages for debugging.
.It Fl d Ar dnsserv
.Nm
will advertise DNS server
.Ar dnsserv
to
.Li _dns._udp.lcl
SRV queries.
.Ar dnsserv
must be a fully qualified canonical DNS name.
.Ar dnsserv
must not point to CNAME record.
Also, it must carry terminating period, like
.Dq Li ns.ietf.org. .
.It Fl h Ar hostname
.Ar hostname
specifies local hostname that
.Nm
will serve against incoming unicast/multicast queries.
If ommitted, result from
.Xr gethostname 3
will be used.
.It Fl i Ar intface
.Ar intface
specifies outgoing interface for multicast queries.
The flag is mandatory.
.It Fl p Ar inport
.Nm
listens to UDP port
.Ar inport
for incoming DNS multicast/unicast queries, or unicast replies.
By default,
.Ar inport
will be 53.
.Fl p
is for debugging purposes only.
.It Fl P Ar outport
.Nm
transmits UDP multicast queries to UDP port
.Ar outport.
By default,
.Ar inport
will be 53.
.Fl P
is for debugging purposes only
.Po
for running two daemons on a single node for debugging
.Pc .
.El
.\"
.Sh EXAMPLES
First, run
.Nm
on UDP port 53
.Pq standard DNS UDP port .
You need to be root to issue
.Xr bind 2
to privileged port.
.Bd -literal -offset indent
# mdnsd -6 -i wi0
.Ed
.Pp
Then, configure
.Xr resolv.conf 5
to ask names to
.Nm
on the local node.
.Bd -literal -offset indent
search itojun.org
nameserver ::
.Ed
.Pp
DNS queries from normal application will be routed to
.Nm Ns .
.Nm
will forward the query to multicast DNS servers.
.Nm
also acts as multicast DNS server for the local hostname.
When a query from adjacent node reach
.Nm Ns ,
.Nm
will transmit appropriate reply to the querier.
.\"
.Sh SEE ALSO
.Rs
.%A Bernard Aboba
.%A Dave Thaler
.%A Levon Esibov
.%D March 9, 2000
.%T Multicast DNS
.%R internet draft
.%N draft-aboba-dnsext-mdns-00.txt
.%O work in progress material
.Re
.\"
.Sh HISTORY
The
.Nm
command first appeared in WIDE/KAME IPv6 protocol stack kit.
.\"
.Sh BUGS
.Nm
does not become daemon at this moment.
.Pp
.Nm
does not handle DNS queries/replies over TCP transport.
.Pp
Some of
.Pq or most of
the features are not implemented yet.
.Pp
Since there is no standard IPv6 multicast address assigned for multicast DNS,
we use linklocal all-node multicast address at this moment.
.Pp
IPv4 mode does not work at this moment.
