.\" Copyright (C) 1999 WIDE Project.
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.\"	$Id: mprecv.8,v 1.1.1.1 1999/12/06 06:26:33 jinmei Exp $
.\"
.Dd Nov 13, 1999
.Dt MPRECV 1
.Os KAME
.\"
.Sh NAME
.Nm mprecv
.Nd a daemon program to receive multicast udp packets
.\"
.Sh SYNOPSIS
.Nm mprecv
.Op Fl d
.Op Fl p Ar port
.Op Fl v
.Op Fl D Ar dumpfile
.Op Fl H Ar history
.Op Fl L Ar logfile
.Op Fl T Ar loginterval
.Op Fl X Ar expire
.Fl i Ar interface
.Fl m Ar mcastaddr
.\"
.Sh DESCRIPTION
The
.Nm
program is designed for measure multicast routing stability in IPv6
network used with
.Xr mpsend 8
program.
The
.Nm
receives UDP packets sent to multicast address
.Ar mcastaddr
using
.Ar interface .
.Pp
The options are as follows:
.Bl -tag -width Fl
.It Fl d
Specify the
.Nm
to run in daemon mode. 
.It Fl p Ar port
Specify the UDP port number. Default value is 9998.
.It Fl D Ar dumpfile
Specify the name of dumpfile. By default
.Pa /tmp/mprecv.dump
is used.
.It Fl H Ar history
Specify the number of "packet lost" history kept for each logging
interval.
.It Fl L Ar logfile
Specify the name of logfile. By default
.Pa /var/log/mprecv.log
is used.
.It Fl T Ar loginterval
Specify the interval of status dump to
.Ar logfile
in second.
The default value is 3600 sec (1 hour).
.It Fl X Ar expire
Specify the expire time in day to delete idle session records.
Default value is 7 days.
.It Fl v
Enable the debug output and prevent the
.Nm
go into daemon mode.
.El
.Pp
The
.Nm
program also writes status dump to
.Ar dumpfile
when it receives a SIGINFO signal.
SIGWINCH signal reset the interval measuring variables.
.\"
.Sh SEE ALSO
.Xr mpsend 8
.\"
.Sh HISTORY
The
.Nm
command first appeared in WIDE/KAME IPv6 protocol stack kit.
.\"
.Sh BUGS
IPv4 is not supported.
