# New ports collection makefile for:	ct
# Date created:		5 Apr 1999 17:00 JST
# Whom:			TANAKA Takashi <tanaka@tahi.org>
#
# $Id: Makefile,v 1.2 1999/08/13 02:38:50 itojun Exp $
#

DISTNAME=	ct-0.3
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.tahi.org/pub/TAHI/ct/
# you might need debugging, it's a developer release !
#CFLAGS+=	-g

MAINTAINER=	tanaka@tahi.org

USE_PERL5=      yes
NO_BUILD=	yes

V6EVALDIR=	${PREFIX}/v6eval

#RUN_DEPENDS=	$(V6EVALDIR):v6eval \

.include <bsd.port.mk>
