.\" Copyright (C) 1995, 1996, 1997, and 1998 WIDE Project.
.\" All rights reserved.
.\" 
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of the project nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE PROJECT AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE PROJECT OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.Dd Aug 13, 1999
.Dt RACOON.CONF 5
.Os KAME
.\"
.Sh NAME
.Nm racoon.conf
.Nd configuration file for racoon
.\"
.\" .Sh SYNOPSIS
.\"
.Sh DESCRIPTION
.Nm
is the configuration file for the
.Xr racoon 8
ISAKMP daemon,
negotiating security association for myself and IPsec.
This is consists of a sequence of directives and statements like C code.
Each directives are composed by a tag and a enclosed by '{' and '}'
in which some statements are composed of tokens separated by white space,
which can be any combination of blanks, tabs.
Lines beginning with
.Ql #
are comments.
.\"
.Ss Meta Syntax
Keywords and special characters that the parser expects exactly are
displayed using the
.Ic bold
font.
Parameters are specifying with
.Ar underline .
Parameters shown in
square brackets
.Po
.Sq [
and
.Sq ]
.Pc
are used to show optional keywords and parameters.
The vertical bar
.Pq Sq \*(Ba
is used to indicate
between a choice of optional parameters.
Parentheses
.Po
.Sq (
and
.Sq )
.Pc
are used to group keywords and parameters when necessary.
Major parameters are listed below.
.Pp
.Bl -tag -width addressx -compact
.It Ar number
means hexa-decimal or decimal number.  The former is expressed with '0x'.
.It Ar string
.It Ar path
.It Ar file
means any string enclosed
.Sq \&"
.Pq double quote .
.It Ar address
means IPv6 and IPv4 address.
.It Ar port
means TCP/UDP port number.
.It timeunit
is one of following:
sec, secs, second, seconds, min, mins, minute, minutes, hour, hours.
.It byteunit
is one of following: B, byte, bytes, KB, MB, TB.
.El
.\"
.Ss Path Specification
.Bl -tag -width Ds -compact
.It Ic path include Ar path ;
specifies a path to include file.  See
.Ic File Include .
.It Ic path pre_shared_key Ar file ;
specifies a file including pre-shared key for various ID.
This file includes some lines of a pair of
.Ar ID
and
.Ar key .
.Ar ID
and
.Ar key
are separated by any number of blanks and/or tab characters.
.It Ic path certificate Ar path ;
racoon will search this directory if the certificate or certificate request
is received.
.El
.\"
.Ss File Include
.Bl -tag -width Ds -compact
.It Ic include Ar file
other configuration file can be included.
.El
.\"
.Ss Identifier Specification
.Bl -tag -width Ds -compact
.It Ic identifier Ic vendor_id Ar string ;
defines Vendor ID.
.It Ic identifier Ic user_fqdn Ar string ;
defines my USER_FQDN included ID payload.
.It Ic identifier Ic fqdn Ar string ;
defines my FQDN included ID payload.
.It Ic identifier Ic keyid Ar file ;
defines my KEY_ID included ID payload.
.El
.\"
.Ss Timer Specification
.Bl -tag -width Ds -compact
.It Ic timer { Ar statements Ic }
specifys default various timer.
.Pp
.Bl -tag -width Ds -compact
.It Ic counter Ar number ;
maximun trying count to send.
.It Ic interval Ar number Ar timeunit ;
maximun interval to resend.
.It Ic persend Ar number ;
the number of packets per a send.
.It Ic phase1 Ar number Ar timeunit ;
.It Ic phase2 Ar number Ar timeunit ;
timer for waiting to complete each phase.
.El
.El
.\"
.Ss Listening Port Specification
.Bl -tag -width Ds -compact
.It Ic listen { Ar statements Ic }
If no
.Ar listen
directive is specified,
.Xr racoon 8
will listen to all available interface addresses.
The followings are the list of statements.
.Pp
.Bl -tag -width Ds -compact
.It Ic isakmp Ar address [ Ar port ] ;
If this(these) is specifyed,
.Xr racoon 8
will only listen to its address.
.It Ic admin Ic [ Ar port ] ;
specify the port for connecting to
.Xr kmpstat 8 .
.El
.El
.\"
.Ss Remote Nodes Specifications 
.Bl -tag -width Ds -compact
.It Xo
.Ic remote ( Ar address \*(Ba Ic anonymous ) [
.Ar port ]
.Ic { Ar statements Ic }
.Xc
definies the parameters of IKE phase 1 per remote node.
The followings are the list of statements.
.Pp
.Bl -tag -width Ds -compact
.\"
.It Ic exchange_mode ( main \*(Ba aggressive \*(Ba base ) ;
defined exchange mode of phase 1.
.\"
.It Ic doi Ar ipsec_doi ;
means to use IPSEC-DOI specifyed RFC 2407.
It must be stated.
.\"
.It Ic situation Ic identity_only ;
It must be stated.
.\"
.It Ic dh_group Ar group ;
define the group of Diffie-Hellman exponentiations for aggressive mode.
.Ar group
are one of the following:
.Ic modp768 , modp1024 , modp1536 .
.\"
.It Ic identifier Ar idtype ;
specifies ID type to use phase 1 negotiation.
.Ar idtype
is one of following:
.Ic address , fqdn , user_fqdn , keyid .
These are linked to
.Ic identifier
directive.
.\"
.It Ic certificate_type Ar certtype ;
specifies certificate type.
.Ar certtype
is one of followings:
.Ic x509 , pkcs7 , pgp .
.\"
.It Ic lifetime time Ar number Ar timeunit ;
.It Ic lifetime byte Ar number Ar byteunit ;
define default lifetime of phase 1 SA.
.\"
.It Ic keepalive
Not yet.
.\"
.It Ic nonce_size Ar number ;
define the byte size of nonce value.
.\"
.It Xo
.Ic proposal { Ar sub-substatements Ic }
.Xc
.Bl -tag -width Ds -compact
.\"
.It Ic encryption_algorithm Ar algorithm ;
define encryption algorithm for phase 1 negotiation.
.Ar algorithm
is one of following:
.Ic des , 3des , idea , blowfish , rc5 , cast
for oakley.
In the case of other transform, must not use this statement.
.\"
.It Ic hash_algorithm Ar algorithm;
define hash algorithm for phase 1 negotiation.
.Ar algorithm
is one of following:
.Ic md5, sha1
for oakley.
.\"
.It Ic authentication_method Ar type ;
define the authentication method for phase 1 negotiation.
.Ar type
is only one:
.Ic pre_shared_key, rsasig , dsssig , rsaenc , rsarev .
.\"
.It Ic dh_group Ar group ;
define the group of Diffie-Hellman exponentiations.
.Ar group
is one of following:
.Ic modp768 , modp1024 , modp1536 .
.\"
.It Ic strength Ar level ;
specifies strength of cryptographic algorithm.
.Ar level
is one of following: extra_high, high, normal.
.It Ic lifetime time Ar number Ar timeunit ;
.It Ic lifetime byte Ar number Ar byteunit ;
define lifetime of phase 1 SA eay proposal.
.El
.El
.El
.\"
.Ss Policy Specifications 
.Bl -tag -width Ds -compact
.It Xo
.Ic policy Ar address_range Ar direction Ar action
.Ic { Ar statements Ic }
.Xc
definies a action of matched packet.
.Ar address_range
is 
.Ar source_range Ar destination_range Ar protocol .
.Pp
.Bl -tag -width Ds -compact
.\"
.It Ic pfs_group Ar group ;
define the group of Diffie-Hellman exponentiations.
.Ar group
is one of following:
.Ic modp768 , modp1024 , modp1536 .
.\"
.It Xo
.Ic proposal
.Ic { Ar sub-substatements Ic }
.Xc
.Bl -tag -width Ds -compact
.\"
.It Xo
.Ic protocol Ar protocol
.Ic { Ar sub-substatements Ic }
.Xc
.Ar protocol
is one of followins:
.Ic esp , ah
or
.Ic ipcomp .
.Pp
.Ic esp
means
.Do
IP Encapsulating Security Payload
.Dc ,
RFC 2406.
.Ic ah
means
.Do
IP Authentication Header
.Dc ,
RFC 2402.
.Ic ipcomp
means
.Do
IP Payload Compression Protocol
.Dc ,
RFC 2393.
.Pp
.Bl -tag -width Ds -compact
.\"
.It Ic authentication_algorithm Ar algorithm ;
.Ic hmac_md5, hmac_sha1, none
for esp and ah.
.\"
.It Ic level Ar level ;
.Ar level
is one of following:
.Ic use , require ;
.\"
.It Ic mode Ar mode ;
.Ar mode
is one of following:
.Ic tunnel , transport .
.Ic tunnel
must be with perr's address.
.\"
.It Ic strength Ar level ;
specifies strength of cryptographic algorithm.
.\"
.It Ic nonce_size Ar number ;
define the byte size of random value.
.\"
.It Ic lifetime Ar number Ar type ;
Ar type is one of followings: second or KB.
But in the case of oakley, KB is not supported now.
.El
.El
.El
.El
.\"
.Ss Algorithm Strength Specification
.Bl -tag -width Ds -compact
.It Ic algorithm_strength { Ar statements Ic }
specifies algorithm strength.  These are extracted into attribute of
proposal to negotiate SA.  There are seven type of class;
ISAKMP authentication method,
ISAKMP encryption algorithm,
ISAKMP hash algorithm,
ISAKMP DH group,
IPsec encryption algorithm,
IPsec authentication algorithm,
IPsec compression algorithm.
.Pp
.Bl -tag -width Ds -compact
.It Ic algorithm_class { Ar statements Ic }
.Ic Algorithm_class
is one of following:
isakmp_auth_method isakmp_encryption, isakmp_hash,
isakmp_dh_group, ipsec_encryption, ipsec_authentication,
ipsec_ipcomp.
Each class can be defined three level; "normal", "high" and "extra_high".
Each level can be omited.  If so, it is interpreted that there is no
algorithm appropreately for use in its level.  algorithm type may be
defined at multiple level.
.El
.El
.\"
.Ss Static SA configuration
.Bl -tag -width Ds -compact
.It Ic static_sa Ar parameters
specifies static SA.  This
.Ar parameters
will be passed to
.Xr setkey 8 .
Not yet, but only define.
.El
.\"
.Ss Specifying log file
.Bl -tag -width Ds -compact
.It Ic log ( Ar number \*(Ba Ar level ) ;
define dump level.  It is debugging use.
.Ar is one of following:
.Ic info , notify , debug , debug2 , debug3 , debug4 .
.El
.\"
.Ss Specifying the way to pad
.Bl -tag -width Ds -compact
.It Ic padding { Ar statements Ic }
specifyed padding format.
The followings are the list of statements.
.Bl -tag -width Ds -compact
.It Ic maximum_length Ar number ;
.It Ic randomize (on \(ba off) ;
.It Ic restrict_check (on \(ba off) ;
.It Ic exclusive_tail (on \(ba off) ;
.El
.El
.\"
.Sh EXAMPLE
The following shows how remote directive should be configured.
.Bd -literal -offset
remote 172.168.2.2 [7000]
{
	exchange_mode main;

	# default doi is "ipsec_doi".
	doi ipsec_doi;

	# default situation is "identity_only".
	situation identity_only;

	# specify the identifier type
	# "address", "fqdn", "user_fqdn", "keyid"
	identifier user_fqdn;
	certificate_type pgp;

	# specify the bytes length of nonce.
	nonce_size 16;

	# means to do keep-a-live.  This should not be used in dial-up.
	keepalive;

	# default lifetime inlayed each proposals.
	lifetime time 10 min;	# sec,min,hour
	lifetime byte 5 MB;	# B,KB,GB

	proposal {
		strength normal;
		authentication_method rsasig ;
	}
	proposal {
		strength high;
		authentication_method pre_shared_key ;

		# they can be defined individually.
		lifetime time 5 min;
		lifetime byte 2 MB;
	}
	proposal {
		# they can be defined explicitly.
		encryption_algorithm des;
		hash_algorithm md5;
		dh_group modp1024;
		authentication_method pre_shared_key ;
	}
}
.Ed
.Pp
The following example shows how policy directives should be configured.
.Bd -literal -offset
# Fot example.
# 10.1.1.0/24                  10.2.2.0/24
#     --+--                      --+--
#       |                          |
#     +-+-+                      +-+-+
#     | A |==========//==========| B |
#     +---+                      +-+-+
#       172.168.1.1      172.168.2.2
# setting on gateway A:

policy 10.1.1.0/24 10.2.2.0/24 any inout ipsec
{
	# "pfs_group" specifies to require PFS, and defines a DH group number.
	# It is followed by either "modp768", "modp1024" or "modp1536".
	pfs_group modp768;

	# "proposal" defines proposal of IPsec-SA.

	# This proposal means IP2|ESP|IP1|ULP.
	proposal {
		# "lifetime" specifies two type of lifetime of SA.
		lifetime time 200 second;
		lifetime byte 5000 KB;

		# "protocol" defines some of trasnform.
		protocol esp {
			# "level" can be followed by either "require", "use" or
			# "default".  "default" is used if there is no "level".
			level require ;

			# "mode" can be followed by either "tunnel" or "use".
			# If tunnel mode is specified, peer's address must be
			# specifyed carefully.
			mode tunnel 172.168.2.2;

			# "strength" defines a strength of algorithm in use.
			# This is either "extra_high", "high" or "normal".
			strength high ;
		}
	}

	# This proposal means IP2|AH|ESP|IP1|ULP.
	# The order of protocol is very important.  It means SA bundle or
	# nested SAs.
	proposal {
		# "lifetime" specifies some lifetime of SA.
		lifetime time 300 second;
		lifetime byte 10000 KB;

		protocol esp {
			level require ;
			mode tunnel 172.168.2.2;
			strength high ;
		}

		# "ah" means AH.
		protocol ah {
			level require ;
			mode transport ;	# NOTE: not tunnel.
			strength high ;
		}
	}
}
.Ed
.\"
.Sh SEE ALSO
.Xr kmpstat 8 ,
.Xr racoon 8
.\"
.Sh HISTORY
The
.Nm
configuration file first appeared in
.Dq YIPS
Yokogawa IPsec implementation.
.\"
.Sh BUGS
Some statements may not be implemented.
These will be worked in the future.
