# $NetBSD: Makefile,v 1.36 1998/09/05 20:20:03 frueauf Exp $
# FreeBSD Id: Makefile,v 1.117 1997/08/16 03:11:52 gpalmer Exp 
#

.include "../mk/bsd.prefs.mk"

    SUBDIR += altq
    SUBDIR += bind8
    SUBDIR += gated-ipv6
    SUBDIR += irc
    SUBDIR += mrt
    SUBDIR += ncftp3
    SUBDIR += newbie
    SUBDIR += rsync
    SUBDIR += socks64
    SUBDIR += tcptrace
    SUBDIR += ucd-snmp
    SUBDIR += v6tun
    SUBDIR += wget
    SUBDIR += wu-ftpd
    SUBDIR += zebra

.include "../mk/bsd.pkg.subdir.mk"
