# New ports collection makefile for:	echoping
# Version required:	2.2.0
# Date created:		13 April 1997
# Whom:			peter
#
# $FreeBSD: ports/net/echoping/Makefile,v 1.5 1999/08/31 06:48:45 mharo Exp $
#

DISTNAME=	echoping-2.2.0
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.internatif.org/pub/unix/echoping/

PATCHFILES=	echoping-2.2.0-v6-20000201.diff.gz
PATCH_SITES=	ftp://ftp.kame.net/pub/kame/misc/
PATCH_DIST_STRIP=	-p1

MAINTAINER=	sumikawa@kame.net

MAN1=		echoping.1

.include <bsd.port.mk>
