# New ports collection makefile for:	v6tun
# Date created:		Tue Jun  9 13:38:11 JST 1998
# Whom:			Jun-ichiro itojun Itoh <itojun@itojun.org>
#
# $KAME: Makefile,v 1.2 2000/06/25 10:58:49 sumikawa Exp $
#

PORTNAME=	v6tun
PORTVERSION=	1.1
CATEGORIES=	net
MASTER_SITES=	ftp://ftp.kyoto.wide.ad.jp/IPv6/v6tun/

MAINTAINER=	itojun@itojun.org

.include <bsd.port.mk>
