# $Id: Makefile,v 1.3 2000/04/20 09:22:22 itojun Exp $

     SUBDIR += bind8
     SUBDIR += libpcap
     SUBDIR += pchar
     SUBDIR += tcpdump
     SUBDIR += totd
     SUBDIR += ucd-snmp
     SUBDIR += zebra

.include <bsd.port.subdir.mk>
