SUBDIR+=bgpd dtcp faithd gifconfig hroute6d icmp6dump ifmcstat inetd lpr \
	mping mld6query ndp pim6dd pim6sd pma prefix racoon rip6query route6d \
	rrenumd rtadvd rtsold setkey tcpdump traceroute traceroute6 trpt
#SUBDIR+=inet6d

.include <bsd.subdir.mk>
