SUBDIR+=bgpd dtcp faithd gifconfig hroute6d icmp6dump ifmcstat inetd lpr \
	mping mld6query ndp pim6dd pim6sd prefix racoon rip6query route6d \
	rrenumd rtadvd rtsold setkey traceroute traceroute6 trpt
SUBDIR+=altqd pvcbridge pvcsif pvctxctl tbrconfig
#SUBDIR+=natptconfig natptlog
#SUBDIR+=inet6d

.include <bsd.subdir.mk>
