# $NetBSD$
#

DISTNAME=	pchar-1.0
CATEGORIES=	net
MASTER_SITES=	http://www.ca.sandia.gov/~bmah/Software/pchar/

MAINTAINER=	itojun@itojun.org
HOMEPAGE=	http://www.zebra.org/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=--with-ipv6

.include "../../mk/bsd.pkg.mk"
