# $OpenBSD$
# $Id: Makefile,v 1.3 2000/01/26 15:02:03 itojun Exp $

DISTNAME=	pchar-1.1.1
CATEGORIES=	net
MASTER_SITES=	http://www.ca.sandia.gov/~bmah/Software/pchar/

MAINTAINER=	itojun@itojun.org
HOMEPAGE=	http://www.ca.sandia.gov/~bmah/Software/pchar/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=--with-ipv6=/usr/local/v6

.include <bsd.port.mk>
