# $OpenBSD$
# $Id: Makefile,v 1.2 1999/11/05 00:40:53 itojun Exp $

DISTNAME=	pchar-1.0
CATEGORIES=	net
MASTER_SITES=	http://www.ca.sandia.gov/~bmah/Software/pchar/

MAINTAINER=	itojun@itojun.org
HOMEPAGE=	http://www.ca.sandia.gov/~bmah/Software/pchar/

GNU_CONFIGURE=	yes
CONFIGURE_ARGS+=--with-ipv6

.include <bsd.port.mk>
