# $FreeBSD: src/usr.sbin/lpr/Makefile,v 1.4.2.1 1999/08/29 15:43:00 peter Exp $

#SUBDIR=	common_source chkprintcap lp lpc lpd lpq lpr lprm lptest pac \
#	filters filters.ru SMM.doc
SUBDIR= common_source lpc lpd lpq lpr lprm pac

.include <bsd.subdir.mk>


